return {
    ["reraise"] = {name="Instant Reraise", option=7, key_item=false, offset=4},
    ["wing"] = {name="Daedalus Wing", option=263, key_item=false, offset=26},
    ["status"] = {name="Catholicon", option=519, key_item=false, offset=14},
    ["atk"] = {name="Barbarian's Drink", option=1031, key_item=false, offset=21},
    ["da"] = {name="Fighter's Drink", option=1287, key_item=false, offset=6},
    ["matk"] = {name="Oracle's Drink", option=1543, key_item=false, offset=22},
    ["macc"] = {name="Assassin's Drink", option=1799, key_item=false, offset=5},
    ["acc"] = {name="Spy's Drink", option=2055, key_item=false, offset=8},
    ["brave"] = {name="Braver's Drink", option=2311, key_item=false, offset=15},
    ["soldier"] = {name="Soldier's Drink", option=2567, key_item=false, offset=17},
    ["crit"] = {name="Champion's Drink", option=2823, key_item=false, offset=9},
    ["regain"] = {name="Monarch's Drink", option=3079, key_item=false, offset=20},
    ["enmity"] = {name="Gnostic's Drink", option=3335, key_item=false, offset=7},
    ["statusall"] = {name="Cleric's Drink", option=3591, key_item=false, offset=30},
    ["pot1"] = {name="Lucid Potion I", option=4103, key_item=false, offset=0},
    ["pot2"] = {name="Lucid Potion II", option=4359, key_item=false, offset=10},
    ["pot3"] = {name="Lucid Potion III", option=4615, key_item=false, offset=23},
    ["ether1"] = {name="Lucid Ether I", option=4871, key_item=false, offset=1},
    ["ether2"] = {name="Lucid Ether II", option=5127, key_item=false, offset=11},
    ["ether3"] = {name="Lucid Ether III", option=5383, key_item=false, offset=24},
    ["elixir"] = {name="Lucid Elixir I", option=5639, key_item=false, offset=25},
    ["wings1"] = {name="Lucid Wings I", option=5895, key_item=false, offset=13},
    ["doom"] = {name="Savior's Tonic", option=7175, key_item=false, offset=27},
    ["petrify"] = {name="Mirror's Tonic", option=7431, key_item=false, offset=28},
    ["amnesia"] = {name="Moneta's Tonic", option=7687, key_item=false, offset=29},
    ["terror"] = {name="Steadfast Tonic", option=7943, key_item=false, offset=31},
    ["virus"] = {name="Virus Buffer", option=11271, key_item=false, offset=44},
    ["charm"] = {name="Charm Buffer", option=11527, key_item=false, offset=45},
    ["curse"] = {name="Curse Buffer", option=11783, key_item=false, offset=46},
}
