return {
	['Warlock\'s Roll']={'warlock','macc','magic ac','rdm'},
	['Fighter\'s Roll']={'fight','double','dbl','war'},
	['Monk\'s Roll']={'monk','subtle','mnk'},
	['Healer\'s Roll']={'heal','cure','whm'},
	['Wizard\'s Roll']={'wizard','matk','magic at','blm'},
	['Rogue\'s Roll']={'rogue','crit','thf'},
	['Gallant\'s Roll']={'gallant','def','pld'},
	['Chaos Roll']={'chaos','attack','atk','drk'},
	['Beast Roll']={'beast','pet at','bst'},
	['Choral Roll']={'inter','spell inter','brd'},
	['Hunter\'s Roll']={'hunt','acc','rng'},
	['Samurai Roll']={'sam','stp','store'},
	['Ninja Roll']={'nin','eva'},
	['Drachen Roll']={'drach','pet ac','drg'},
	['Magus\'s Roll']={'magus','mdb','magic d','blu'},
	['Corsair\'s Roll']={'cor','exp'},
	['Puppet Roll']={'pup', 'pet m'},
	['Dancer\'s Roll']={'dance','regen','dnc'},
	['Scholar\'s Roll']={'sch','conserve m'},
	['Bolter\'s Roll']={'bolt','move','flee','speed'},
	['Courser\'s Roll']={'course','snap'},
	['Blitzer\'s Roll']={'blitz','delay'},
	['Tactician\'s Roll']={'tact','regain'},
	['Allies\' Roll']={'all','skillchain'},
	['Miser\'s Roll']={'miser','save tp','conserve t'},
	['Companion\'s Roll']={'companion','pet r'},
	['Avenger\'s Roll']={'avenge','counter'},
	['Naturalist\'s Roll']={'natural','enhance','duration','nature'},
	['Runeist\'s Roll']={'run','meva','magic e'},
	
}