-- Generated by the Organizer Library (Sun Jul 14 22:30:59 2019)
return {
    [1]={
        ["log_name"]="hasty pinion +1", 
        ["id"]=21363, 
        ["name"]="hasty pinion +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="kentarch belt +1", 
        ["id"]=28413, 
        ["name"]="kentarch belt +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="shadow ring", 
        ["id"]=14646, 
        ["name"]="shadow ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="carmine mask", 
        ["count"]=1, 
        ["id"]=26678, 
        ["name"]="carmine mask", 
        ["augments"]={
            [1]="Accuracy+15", 
            [2]="Mag. Acc.+10", 
            [3]="\"Fast Cast\"+3"
        }
    }, 
    [5]={
        ["log_name"]="ginsen", 
        ["id"]=21371, 
        ["name"]="ginsen", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="valorous mask", 
        ["id"]=25641, 
        ["name"]="valorous mask", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="begrudging ring", 
        ["id"]=26172, 
        ["name"]="begrudging ring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="flume belt +1", 
        ["id"]=28437, 
        ["name"]="flume belt +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="leyline gloves", 
        ["count"]=1, 
        ["id"]=27135, 
        ["name"]="leyline gloves", 
        ["augments"]={
            [1]="Accuracy+15", 
            [2]="Mag. Acc.+15", 
            [3]="\"Mag.Atk.Bns.\"+15", 
            [4]="\"Fast Cast\"+3"
        }
    }, 
    [10]={
        ["log_name"]="olympus sash", 
        ["id"]=10821, 
        ["name"]="olympus sash", 
        ["count"]=1
    }
}