-- Generated by the Organizer Library (Sat Dec 15 08:48:26 2018)
return {
    [1]={
        ["log_name"]="kentarch belt +1", 
        ["id"]=28413, 
        ["name"]="kentarch belt +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="ginsen", 
        ["id"]=21371, 
        ["name"]="ginsen", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="xucau mantle", 
        ["id"]=27614, 
        ["name"]="xucau mantle", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="flume belt +1", 
        ["id"]=28437, 
        ["name"]="flume belt +1", 
        ["count"]=1
    }
}