-- Generated by the Organizer Library (Sun Jul 14 22:30:59 2019)
return {
    [1]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="homiliary", 
        ["id"]=22268, 
        ["name"]="homiliary", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="lissome necklace", 
        ["id"]=26004, 
        ["name"]="lissome necklace", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="sheltered ring", 
        ["id"]=10764, 
        ["name"]="sheltered ring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="hippomenes socks", 
        ["id"]=27409, 
        ["name"]="hippomenes socks", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="moonshade earring", 
        ["count"]=1, 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["augments"]={
            [1]="\"Mag.Atk.Bns.\"+4", 
            [2]="TP Bonus +250"
        }
    }, 
    [9]={
        ["log_name"]="friomisi earring", 
        ["id"]=28514, 
        ["name"]="friomisi earring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="grunfeld rope", 
        ["id"]=28408, 
        ["name"]="grunfeld rope", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="dudgeon earring", 
        ["id"]=28522, 
        ["name"]="dudgeon earring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="globidonta ring", 
        ["id"]=28539, 
        ["name"]="globidonta ring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="ethereal earring", 
        ["id"]=15965, 
        ["name"]="ethereal earring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="prolix ring", 
        ["id"]=10752, 
        ["name"]="prolix ring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="etiolation earring", 
        ["id"]=28478, 
        ["name"]="etiolation earring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="infused earring", 
        ["id"]=28475, 
        ["name"]="infused earring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="apate ring", 
        ["id"]=26173, 
        ["name"]="apate ring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="siegel sash", 
        ["id"]=15960, 
        ["name"]="siegel sash", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="fucho-no-obi", 
        ["id"]=28452, 
        ["name"]="fucho-no-obi", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="impatiens", 
        ["id"]=19761, 
        ["name"]="impatiens", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="enchanter earring +1", 
        ["id"]=28494, 
        ["name"]="enchntr. earring +1", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="sanare earring", 
        ["id"]=28516, 
        ["name"]="sanare earring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="dark ring", 
        ["id"]=14644, 
        ["name"]="dark ring", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="heartseeker earring", 
        ["id"]=28523, 
        ["name"]="heartseeker earring", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="twilight torque", 
        ["id"]=11625, 
        ["name"]="twilight torque", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="merciful cape", 
        ["id"]=15471, 
        ["name"]="merciful cape", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="patricius ring", 
        ["id"]=28578, 
        ["name"]="patricius ring", 
        ["count"]=1
    }
}