-- Generated by the Organizer Library (Mon Apr  1 19:58:50 2019)
return {
    [1]={
        ["log_name"]="foire tobe +1", 
        ["id"]=27845, 
        ["name"]="foire tobe +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="domesticator's earring", 
        ["id"]=28505, 
        ["name"]="domes. earring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="epona's ring", 
        ["id"]=11651, 
        ["name"]="epona's ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="lissome necklace", 
        ["id"]=26004, 
        ["name"]="lissome necklace", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="dark ring", 
        ["count"]=1, 
        ["id"]=14644, 
        ["name"]="dark ring", 
        ["augments"]={
            [1]="Magic dmg. taken -5%", 
            [2]="Phys. dmg. taken -5%"
        }
    }, 
    [8]={
        ["log_name"]="grunfeld rope", 
        ["id"]=28408, 
        ["name"]="grunfeld rope", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="clotharius torque", 
        ["id"]=26017, 
        ["name"]="clotharius torque", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="foire babouches +1", 
        ["id"]=28261, 
        ["name"]="foire bab. +1", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="foire dastanas +1", 
        ["id"]=27981, 
        ["name"]="foire dastanas +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="ethereal earring", 
        ["id"]=15965, 
        ["name"]="ethereal earring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="steelflash earring", 
        ["id"]=28520, 
        ["name"]="steelflash earring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="etiolation earring", 
        ["id"]=28478, 
        ["name"]="etiolation earring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="twilight torque", 
        ["id"]=11625, 
        ["name"]="twilight torque", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="cessance earring", 
        ["id"]=27541, 
        ["name"]="cessance earring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="moonshade earring", 
        ["count"]=1, 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["augments"]={
            [1]="\"Mag.Atk.Bns.\"+4", 
            [2]="TP Bonus +250"
        }
    }, 
    [20]={
        ["log_name"]="apate ring", 
        ["id"]=26173, 
        ["name"]="apate ring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="visucius's mantle", 
        ["count"]=1, 
        ["id"]=26263, 
        ["name"]="visucius's mantle", 
        ["augments"]={
            [1]="Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Pet: Accuracy+10 Pet: Rng. Acc.+10", 
            [4]="Pet: \"Regen\"+10", 
            [5]="System: 1 ID: 1247 Val: 4"
        }
    }, 
    [23]={
        ["log_name"]="sanctity necklace", 
        ["id"]=26023, 
        ["name"]="sanctity necklace", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="thurandaut ring", 
        ["id"]=27589, 
        ["name"]="thurandaut ring", 
        ["count"]=1
    }
}