-- Generated by the Organizer Library (Sat Dec 29 15:27:47 2018)
return {
    [1]={
        ["log_name"]="cessance earring", 
        ["id"]=27541, 
        ["name"]="cessance earring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="rajas ring", 
        ["id"]=15543, 
        ["name"]="rajas ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="mecistopins mantle", 
        ["id"]=27596, 
        ["name"]="mecisto. mantle", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="ethereal earring", 
        ["id"]=15965, 
        ["name"]="ethereal earring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="etiolation earring", 
        ["id"]=28478, 
        ["name"]="etiolation earring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="twilight helm", 
        ["id"]=11798, 
        ["name"]="twilight helm", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="lissome necklace", 
        ["id"]=26004, 
        ["name"]="lissome necklace", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="sheltered ring", 
        ["id"]=10764, 
        ["name"]="sheltered ring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="moonshade earring", 
        ["count"]=1, 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["augments"]={
            [1]="\"Mag.Atk.Bns.\"+4", 
            [2]="TP Bonus +250"
        }
    }, 
    [14]={
        ["log_name"]="twilight torque", 
        ["id"]=11625, 
        ["name"]="twilight torque", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="apate ring", 
        ["id"]=26173, 
        ["name"]="apate ring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="twilight mail", 
        ["id"]=11362, 
        ["name"]="twilight mail", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }
}