-- Generated by the Organizer Library (Fri Dec 21 18:46:40 2018)
return {
    [1]={
        ["log_name"]="medium's sabots", 
        ["count"]=1, 
        ["id"]=27493, 
        ["name"]="medium's sabots", 
        ["augments"]={
            [1]="MP+50", 
            [2]="MND+10", 
            [3]="\"Conserve MP\"+7", 
            [4]="\"Cure\" potency +5%"
        }
    }, 
    [2]={
        ["log_name"]="resonance ring", 
        ["id"]=27553, 
        ["name"]="resonance ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="gyve doublet", 
        ["id"]=25708, 
        ["name"]="gyve doublet", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="barkarole earring", 
        ["id"]=27526, 
        ["name"]="barkaro. earring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="vanya hood", 
        ["count"]=1, 
        ["id"]=26797, 
        ["name"]="vanya hood", 
        ["augments"]={
            [1]="MP+50", 
            [2]="\"Cure\" potency +7%", 
            [3]="Enmity-6"
        }
    }, 
    [6]={
        ["log_name"]="satlada necklace", 
        ["id"]=27516, 
        ["name"]="satlada necklace", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="telchine gloves", 
        ["id"]=27048, 
        ["name"]="telchine gloves", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="vanir cotehardie", 
        ["id"]=27887, 
        ["name"]="vanir cotehardie", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="mizukage-no-kubikazari", 
        ["id"]=28379, 
        ["name"]="mizu. kubikazari", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="praeco slacks", 
        ["id"]=11972, 
        ["name"]="praeco slacks", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="befouled crown", 
        ["id"]=26790, 
        ["name"]="befouled crown", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="regal pumps", 
        ["id"]=28273, 
        ["name"]="regal pumps", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="merlinic hood", 
        ["count"]=1, 
        ["id"]=25643, 
        ["name"]="merlinic hood", 
        ["augments"]={
            [1]="Mag. Acc.+20 \"Mag.Atk.Bns.\"+20", 
            [2]="INT+3", 
            [3]="Mag. Acc.+15", 
            [4]="\"Mag.Atk.Bns.\"+11"
        }
    }, 
    [14]={
        ["log_name"]="merlinic hood", 
        ["count"]=1, 
        ["id"]=25643, 
        ["name"]="merlinic hood", 
        ["augments"]={
            [1]="\"Mag.Atk.Bns.\"+25", 
            [2]="Magic burst dmg.+10%"
        }
    }, 
    [15]={
        ["log_name"]="mujin band", 
        ["id"]=11672, 
        ["name"]="mujin band", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="channeler's stone", 
        ["id"]=26326, 
        ["name"]="channeler's stone", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="toro cape", 
        ["id"]=28615, 
        ["name"]="toro cape", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="disperser's cape", 
        ["id"]=27606, 
        ["name"]="disperser's cape", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="bookworm's cape", 
        ["count"]=1, 
        ["id"]=28636, 
        ["name"]="bookworm's cape", 
        ["augments"]={
            [1]="INT+3", 
            [2]="Helix eff. dur. +19", 
            [3]="\"Regen\" potency+2"
        }
    }, 
    [20]={
        ["log_name"]="merlinic crackows", 
        ["count"]=1, 
        ["id"]=27497, 
        ["name"]="merlinic crackows", 
        ["augments"]={
            [1]="\"Mag.Atk.Bns.\"+21", 
            [2]="Magic burst dmg.+10%", 
            [3]="VIT+4"
        }
    }, 
    [21]={
        ["log_name"]="helios gloves", 
        ["count"]=1, 
        ["id"]=27049, 
        ["name"]="helios gloves", 
        ["augments"]={
            [1]="Mag. Acc.+25", 
            [2]="\"Fast Cast\"+3", 
            [3]="Magic burst dmg.+7%"
        }
    }, 
    [22]={
        ["log_name"]="serpentes cuffs", 
        ["id"]=15019, 
        ["name"]="serpentes cuffs", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="arbatel bonnet", 
        ["id"]=26778, 
        ["name"]="arbatel bonnet", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="nefer kalasiris", 
        ["id"]=11864, 
        ["name"]="nefer kalasiris", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="telchine chasuble", 
        ["id"]=26894, 
        ["name"]="telchine chas.", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="serpentes sabots", 
        ["id"]=14085, 
        ["name"]="serpentes sabots", 
        ["count"]=1
    }
}