-- Generated by the Organizer Library (Sat Dec 15 20:01:32 2018)
return {
    [1]={
        ["log_name"]="almace", 
        ["id"]=20689, 
        ["name"]="almace", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Crit. hit damage +4%", 
            [2]="STR+12", 
            [3]="Accuracy+11", 
            [4]="Attack+11"
        }
    }, 
    [3]={
        ["log_name"]="colada", 
        ["count"]=1, 
        ["id"]=20677, 
        ["name"]="colada", 
        ["augments"]={
            [1]="Crit.hit rate+3", 
            [2]="DEX+14", 
            [3]="Accuracy+17", 
            [4]="DMG:+7"
        }
    }, 
    [4]={
        ["id"]=20701, 
        ["name"]="iris", 
        ["count"]=1, 
        ["log_name"]="iris"
    }
}