-- Generated by the Organizer Library (Mon Apr  1 19:58:50 2019)
return {
    [1]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Pet: Accuracy+26 Pet: Rng. Acc.+26", 
            [2]="Pet: \"Dbl.Atk.\"+3 Pet: Crit.hit rate +3", 
            [3]="Pet: INT+5", 
            [4]="Pet: \"Mag.Atk.Bns.\"+14"
        }
    }, 
    [2]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Crit. hit damage +4%", 
            [2]="STR+12", 
            [3]="Accuracy+11", 
            [4]="Attack+11"
        }
    }, 
    [3]={
        ["log_name"]="rao togi +1", 
        ["count"]=1, 
        ["id"]=26851, 
        ["name"]="rao togi +1", 
        ["augments"]={
            [1]="Pet: HP+125", 
            [2]="Pet: Accuracy+20", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [4]={
        ["log_name"]="moonbow belt", 
        ["id"]=26340, 
        ["name"]="moonbow belt", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="dispersal mantle", 
        ["id"]=28634, 
        ["name"]="dispersal mantle", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="magoraga bead necklace", 
        ["id"]=11627, 
        ["name"]="magoraga beads", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="buffoon's collar +1", 
        ["id"]=16282, 
        ["name"]="bfn. collar +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="rao kabuto", 
        ["count"]=1, 
        ["id"]=26674, 
        ["name"]="rao kabuto", 
        ["augments"]={
            [1]="Pet: HP+100", 
            [2]="Pet: Accuracy+15", 
            [3]="Pet: Damage taken -3%"
        }
    }, 
    [9]={
        ["log_name"]="tali'ah turban +2", 
        ["id"]=25573, 
        ["name"]="tali'ah turban +2", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="shepherd's chain", 
        ["id"]=16297, 
        ["name"]="shepherd's chain", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="herculean trousers", 
        ["count"]=1, 
        ["id"]=25842, 
        ["name"]="herculean trousers", 
        ["augments"]={
            [1]="Pet: Accuracy+29 Pet: Rng. Acc.+29", 
            [2]="Pet: \"Store TP\"+10", 
            [3]="Pet: INT+5", 
            [4]="Pet: \"Mag.Atk.Bns.\"+9"
        }
    }, 
    [12]={
        ["log_name"]="naga kyahan", 
        ["count"]=1, 
        ["id"]=27459, 
        ["name"]="naga kyahan", 
        ["augments"]={
            [1]="Pet: HP+100", 
            [2]="Pet: Accuracy+25", 
            [3]="Pet: Attack+25"
        }
    }, 
    [13]={
        ["log_name"]="ryuo hakama", 
        ["count"]=1, 
        ["id"]=27300, 
        ["name"]="ryuo hakama", 
        ["augments"]={
            [1]="Accuracy+20", 
            [2]="\"Store TP\"+4", 
            [3]="Phys. dmg. taken -3"
        }
    }, 
    [14]={
        ["log_name"]="klouskap sash", 
        ["id"]=26335, 
        ["name"]="klouskap sash", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="guignol earring", 
        ["id"]=15999, 
        ["name"]="guignol earring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="herculean helm", 
        ["count"]=1, 
        ["id"]=25642, 
        ["name"]="herculean helm", 
        ["augments"]={
            [1]="Pet: Accuracy+27 Pet: Rng. Acc.+27", 
            [2]="Pet: \"Dbl. Atk.\"+4", 
            [3]="Pet: AGI+3", 
            [4]="Pet: Attack+12 Pet: Rng.Atk.+12", 
            [5]="Pet: \"Mag.Atk.Bns.\"+2"
        }
    }, 
    [17]={
        ["log_name"]="herculean helm", 
        ["count"]=1, 
        ["id"]=25642, 
        ["name"]="herculean helm", 
        ["augments"]={
            [1]="\"Triple Atk.\"+3", 
            [2]="AGI+8", 
            [3]="Accuracy+13"
        }
    }, 
    [18]={
        ["log_name"]="rao kote", 
        ["count"]=1, 
        ["id"]=27026, 
        ["name"]="rao kote", 
        ["augments"]={
            [1]="Pet: HP+100", 
            [2]="Pet: Accuracy+15", 
            [3]="Pet: Damage taken -3%"
        }
    }, 
    [19]={
        ["log_name"]="regal pumps", 
        ["id"]=28273, 
        ["name"]="regal pumps", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="isa belt", 
        ["id"]=28451, 
        ["name"]="isa belt", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="varar ring +1", 
        ["id"]=26180, 
        ["name"]="varar ring +1", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="tali'ah manteel +2", 
        ["id"]=25796, 
        ["name"]="tali'ah manteel +2", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="rao haidate", 
        ["count"]=1, 
        ["id"]=27202, 
        ["name"]="rao haidate", 
        ["augments"]={
            [1]="Pet: HP+100", 
            [2]="Pet: Accuracy+15", 
            [3]="Pet: Damage taken -3%"
        }
    }, 
    [24]={
        ["log_name"]="puppetmaster's collar +1", 
        ["id"]=25520, 
        ["name"]="pup. collar +1", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="handler's earring +1", 
        ["id"]=28491, 
        ["name"]="handler's earring +1", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="solemnity cape", 
        ["id"]=26245, 
        ["name"]="solemnity cape", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="visucius's mantle", 
        ["count"]=1, 
        ["id"]=26263, 
        ["name"]="visucius's mantle", 
        ["augments"]={
            [1]="Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Pet: Attack+10 Pet: Rng.Atk.+10", 
            [4]="Pet: Haste+10"
        }
    }, 
    [28]={
        ["log_name"]="visucius's mantle", 
        ["count"]=1, 
        ["id"]=26263, 
        ["name"]="visucius's mantle", 
        ["augments"]={
            [1]="STR+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="STR+10", 
            [4]="Crit.hit rate+10"
        }
    }, 
    [29]={
        ["log_name"]="kyrene's earring", 
        ["id"]=26078, 
        ["name"]="kyrene's earring", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="herculean gloves", 
        ["count"]=1, 
        ["id"]=27140, 
        ["name"]="herculean gloves", 
        ["augments"]={
            [1]="Pet: Accuracy+24 Pet: Rng. Acc.+24", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: Attack+7 Pet: Rng.Atk.+7", 
            [4]="Pet: \"Mag.Atk.Bns.\"+13"
        }
    }
}