-- Generated by the Organizer Library (Sat Mar  6 14:37:10 2021)
return {
    [1]={
        ["log_name"]="souveran cuirass +1", 
        ["id"]=26847, 
        ["name"]="souv. cuirass +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="apeile ring +1", 
        ["id"]=27561, 
        ["name"]="apeile ring +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="brilliance", 
        ["id"]=20705, 
        ["name"]="brilliance", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="brilliance", 
        ["id"]=20705, 
        ["name"]="brilliance", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="jumalik mail", 
        ["id"]=26972, 
        ["name"]="jumalik mail", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="ochain", 
        ["id"]=16193, 
        ["name"]="ochain", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="shadow ring", 
        ["id"]=14646, 
        ["name"]="shadow ring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="unmoving collar", 
        ["id"]=27508, 
        ["name"]="unmoving collar", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="souveran handschuhs +1", 
        ["count"]=1, 
        ["id"]=27023, 
        ["name"]="souv. handsch. +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [10]={
        ["log_name"]="weard mantle", 
        ["id"]=28623, 
        ["name"]="weard mantle", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="apeile ring", 
        ["id"]=27560, 
        ["name"]="apeile ring", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="souveran schaller +1", 
        ["count"]=1, 
        ["id"]=26671, 
        ["name"]="souv. schaller +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [13]={
        ["log_name"]="agema cape", 
        ["id"]=26244, 
        ["name"]="agema cape", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="nourishing earring +1", 
        ["id"]=28485, 
        ["name"]="nourish. earring +1", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="sapience orb", 
        ["id"]=22252, 
        ["name"]="sapience orb", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="eschite greaves", 
        ["count"]=1, 
        ["id"]=27457, 
        ["name"]="eschite greaves", 
        ["augments"]={
            [1]="Mag. Evasion+15", 
            [2]="Spell interruption rate down +15%", 
            [3]="Enmity+7"
        }
    }, 
    [17]={
        ["log_name"]="cryptic earring", 
        ["id"]=28483, 
        ["name"]="cryptic earring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="rudianos's mantle", 
        ["count"]=1, 
        ["id"]=26252, 
        ["name"]="rudianos's mantle", 
        ["augments"]={
            [1]="DEX+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="\"Fast Cast\"+10"
        }
    }, 
    [19]={
        ["log_name"]="iron gobbet", 
        ["id"]=19782, 
        ["name"]="iron gobbet", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="knightly earring", 
        ["id"]=14758, 
        ["name"]="knightly earring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="odyssean greaves", 
        ["count"]=1, 
        ["id"]=27494, 
        ["name"]="odyssean greaves", 
        ["augments"]={
            [1]="Accuracy+25 Attack+25", 
            [2]="STR+4", 
            [3]="Accuracy+7", 
            [4]="Attack+2"
        }
    }, 
    [22]={
        ["log_name"]="nourishing earring", 
        ["id"]=28484, 
        ["name"]="nourish. earring", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="souveran diechlings +1", 
        ["id"]=27199, 
        ["name"]="souv. diechlings +1", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="souveran schuhs +1", 
        ["id"]=27375, 
        ["name"]="souveran schuhs +1", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="shabti cuirass +1", 
        ["id"]=27892, 
        ["name"]="shab. cuirass +1", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="aegis", 
        ["id"]=11927, 
        ["name"]="aegis", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="diemer gorget", 
        ["id"]=27522, 
        ["name"]="diemer gorget", 
        ["count"]=1
    }
}