-- Generated by the Organizer Library (Sun Jul 14 22:30:59 2019)
return {
    [1]={
        ["log_name"]="vanir battery", 
        ["id"]=21380, 
        ["name"]="vanir battery", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="creed sabatons +2", 
        ["id"]=11150, 
        ["name"]="creed sabatons +2", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="apeile ring +1", 
        ["id"]=27561, 
        ["name"]="apeile ring +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="caballarius surcoat", 
        ["id"]=26812, 
        ["name"]="cab. surcoat", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="apeile ring", 
        ["id"]=27560, 
        ["name"]="apeile ring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="caballarius gauntlets", 
        ["id"]=26988, 
        ["name"]="cab. gauntlets", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="brilliance", 
        ["id"]=20705, 
        ["name"]="brilliance", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="caballarius breeches", 
        ["count"]=1, 
        ["id"]=27164, 
        ["name"]="cab. breeches", 
        ["augments"]={
            [1]="Enhances \"Invincible\" effect"
        }
    }, 
    [9]={
        ["log_name"]="eschite greaves", 
        ["id"]=27457, 
        ["name"]="eschite greaves", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="steelflash earring", 
        ["id"]=28520, 
        ["name"]="steelflash earring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="twilight helm", 
        ["id"]=11798, 
        ["name"]="twilight helm", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="bladeborn earring", 
        ["id"]=28521, 
        ["name"]="bladeborn earring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="rudianos's mantle", 
        ["count"]=1, 
        ["id"]=26252, 
        ["name"]="rudianos's mantle", 
        ["augments"]={
            [1]="DEX+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="\"Fast Cast\"+10"
        }
    }, 
    [14]={
        ["log_name"]="andoaa earring", 
        ["id"]=28506, 
        ["name"]="andoaa earring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="nourishing earring +1", 
        ["id"]=28485, 
        ["name"]="nourish. earring +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="caballarius coronet", 
        ["count"]=1, 
        ["id"]=26636, 
        ["name"]="cab. coronet", 
        ["augments"]={
            [1]="Enhances \"Iron Will\" effect"
        }
    }, 
    [17]={
        ["log_name"]="nourishing earring", 
        ["id"]=28484, 
        ["name"]="nourish. earring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="templar sabatons", 
        ["id"]=15699, 
        ["name"]="templar sabatons", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="twilight mail", 
        ["id"]=11362, 
        ["name"]="twilight mail", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="caballarius leggings", 
        ["id"]=27340, 
        ["name"]="cab. leggings", 
        ["count"]=1
    }, 
    [21]={
        ["id"]=28546, 
        ["name"]="capacity ring", 
        ["count"]=1, 
        ["log_name"]="capacity ring"
    }
}