-- Generated by the Organizer Library (Sat Dec 29 15:27:47 2018)
return {
    [1]={
        ["log_name"]="valorous mitts", 
        ["count"]=1, 
        ["id"]=27139, 
        ["name"]="valorous mitts", 
        ["augments"]={
            [1]="Accuracy+23 Attack+23", 
            [2]="Weapon Skill Acc.+1", 
            [3]="Accuracy+11", 
            [4]="Attack+12"
        }
    }, 
    [2]={
        ["log_name"]="valorous mask", 
        ["count"]=1, 
        ["id"]=25641, 
        ["name"]="valorous mask", 
        ["augments"]={
            [1]="Accuracy+16 Attack+16", 
            [2]="\"Store TP\"+6", 
            [3]="AGI+4", 
            [4]="Accuracy+7", 
            [5]="Attack+2"
        }
    }, 
    [3]={
        ["log_name"]="valorous mask", 
        ["count"]=1, 
        ["id"]=25641, 
        ["name"]="valorous mask", 
        ["augments"]={
            [1]="Accuracy+29", 
            [2]="Weapon skill damage +1%", 
            [3]="VIT+7", 
            [4]="Attack+15"
        }
    }, 
    [4]={
        ["log_name"]="kurikaranotachi", 
        ["id"]=21039, 
        ["name"]="kurikaranotachi", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="smertrios's mantle", 
        ["id"]=26257, 
        ["name"]="smertrios's mantle", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="myochin kabuto", 
        ["id"]=13868, 
        ["name"]="myochin kabuto", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="sakonji kote +1", 
        ["id"]=26999, 
        ["name"]="sakonji kote +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="bloodrain strap", 
        ["id"]=21427, 
        ["name"]="bloodrain strap", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="ryuo hakama", 
        ["count"]=1, 
        ["id"]=27300, 
        ["name"]="ryuo hakama", 
        ["augments"]={
            [1]="Accuracy+20", 
            [2]="\"Store TP\"+4", 
            [3]="Phys. dmg. taken -3"
        }
    }, 
    [10]={
        ["log_name"]="valorous greaves", 
        ["count"]=1, 
        ["id"]=27495, 
        ["name"]="valorous greaves", 
        ["augments"]={
            [1]="Weapon skill damage +3%", 
            [2]="STR+5", 
            [3]="Accuracy+15", 
            [4]="Attack+14"
        }
    }, 
    [11]={
        ["log_name"]="valorous greaves", 
        ["count"]=1, 
        ["id"]=27495, 
        ["name"]="valorous greaves", 
        ["augments"]={
            [1]="Accuracy+30", 
            [2]="\"Dbl.Atk.\"+1", 
            [3]="DEX+1", 
            [4]="Attack+7"
        }
    }
}