return {
	['WAR'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 10,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 10,},
			[20] = {["Physical Evasion Bonus"] = 5,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 5,},
			[45] = {["Magic Evasion Bonus"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Accuracy Bonus"] = 5,},
			[80] = {["Fencer Effect"]	=50,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["Critical Hit Bonus"] = 5,},
			[125] = {["Double Attack Effect"] = 2,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Critical Damage Bonus"] = 2,},
			[180] = {["Physical Defense Bonus"] = 15,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 15,},
			[245] = {["Physical Evasion Bonus"] = 8,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 8,},
			[320] = {["Magic Evasion Bonus"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Accuracy Bonus"] = 8,},
			[405] = {["Fencer Effect"] = 50,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Double Attack Effect"] = 2,},
			[500] = {["Superior"] = 3,},
			[500] = {["Critical Damage Bonus"] = 2,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Weapon Skill Damage"] = 3,},
			[605] = {["Physical Defense Bonus"] = 20,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 20,},
			[720] = {["Physical Evasion Bonus"] = 10,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 10,},
			[845] = {["Magic Evasion Bonus"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Accuracy Bonus"] = 10,},
			[980] = {["Fencer Effect"] = 60,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Double Rate Attack"] = 3,},
			[1125] = {["Critical Damage Bonus"] = 3,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Critical Hit Bonus"] = 5,},
			[1280] = {["Physical Defense Bonus"] = 25,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 25,},
			[1445] = {["Physical Evasion Bonus"] = 13,},
			[1530] = {["Physical Accuracy Bonus"] = 13,},
			[1620] = {["Magic Evasion Bonus"] = 13,},
			[1710] = {["Magic Accuracy Bonus"] = 13,},
			[1805] = {["Fencer Effect"] = 70,},
			[1900] = {["Double Attack Effect"] = 3,},
			[2000] = {["Critical Damage Bonus"] = 3,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['MNK'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 5,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 8,},
			[20] = {["Physical Evasion Bonus"] = 6,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 6,},
			[45] = {["Magic Evasion Bonus"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Accuracy Bonus"] = 5,},
			[80] = {["Guarding Skill Bonus"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["Martial Arts Effect"] = 5,},
			[125] = {["Subtle Blow Effect"] = 2,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Counter Effect"] = 2,},
			[180] = {["Physical Defense Bonus"] = 8,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 12,},
			[245] = {["Physical Evasion Bonus"] = 9,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 9,},
			[320] = {["Magic Evasion Bonus"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Accuracy Bonus"] = 8,},
			[405] = {["Guarding Skill Bonus"] = 8,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Subtle Blow Effect"] = 2,},
			[500] = {["Superior"] = 3,},
			[500] = {["Counter Effect"] = 2,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Counter Damage"] = 5,},
			[605] = {["Physical Defense Bonus"] = 10,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 16,},
			[720] = {["Physical Evasion Bonus"] = 12,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 11,},
			[845] = {["Magic Evasion Bonus"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Accuracy Bonus"] = 10,},
			[980] = {["Guarding Skill Bonus"] = 10,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Subtle Blow Effect"] = 3,},
			[1125] = {["Counter Effect"] = 3,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Martial Arts Effect"] = 5,},
			[1280] = {["Physical Defense Bonus"] = 13,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 20,},
			[1445] = {["Physical Evasion Bonus"] = 15,},
			[1530] = {["Physical Accuracy Bonus"] = 15,},
			[1620] = {["Magic Evasion Bonus"] = 13,},
			[1710] = {["Magic Accuracy Bonus"] = 13,},
			[1805] = {["Guarding Skill Bonus"] = 13,},
			[1900] = {["Subtle Blow Effect"] = 3,},
			[2000] = {["Counter Effect"] = 3,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['WHM'] = {
		['Gifts'] = {
			[5] = {["Magic Defense Bonus"] = 7,["Capacity Point Bonus"] = 5,},
			[10] = {["Magic Attack Bonus"] = 3,},
			[20] = {["Magic Evasion Bonus"] = 7,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Magic Accuracy Bonus"] = 7,},
			[45] = {["Physical Accuracy Bonus"] = 2,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Healing Magic Skill"] = 5,},
			[80] = {["Divine Magic Skill"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["New Spell"] = 'Reraise IV',},
			[125] = {["Cure Potency Bonus"] = 5,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Healing Magic Cast Time Decrease"] = 2},
			[180] = {["Magic Defense Bonus"] = 11,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Magic Attack Bonus"] = 5,},
			[245] = {["Magic Evasion Bonus"] = 11,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Magic Accuracy Bonus"] = 11,},
			[320] = {["Physical Accuracy Bonus"] = 3,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Healing Magic Skill"] = 8,},
			[405] = {["Divine Magic Skill"] = 8,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Cure Potency Bonus"] = 5,},
			[500] = {["Superior"] = 3,},
			[500] = {["Healing Magic Cast Time Decrease"] = 2},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Regen Bonus"] = 5,},
			[605] = {["Magic Defense Bonus"] = 14,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Magic Attack Bonus"] = 6,},
			[720] = {["Magic Evasion Bonus"] = 14,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Magic Accuracy Bonus"] = 14,},
			[845] = {["Physical Accuracy Bonus"] = 4,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Healing Magic Skill"] = 10,},
			[980] = {["Divine Magic Skill"] = 10,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Cure Potency Bonus"] = 6,},
			[1125] = {["Healing Magic Cast Time"] = 2,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["New Spell"] = 'Full Cure',},
			[1280] = {["Magic Defense Bonus"] = 18,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Magic Attack Bonus"] = 8,},
			[1445] = {["Magic Evasion Bonus"] = 18,},
			[1530] = {["Magic Accuracy Bonus"] = 18,},
			[1620] = {["Physical Accuracy Bonus"] = 5,},
			[1710] = {["Healing Magic Skill"] = 13,},
			[1805] = {["Divine Magic Skill"] = 13,},
			[1900] = {["Cure Potency Bonus"] = 7,},
			[2000] = {["Healing Magic Cast Time"] = 2,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['BLM'] = {
		['Gifts'] = {
			[5] = {["Magic Defense Bonus"] = 2,["Capacity Point Bonus"] = 5,},
			[10] = {["Magic Attack Bonus"] = 7,},
			[20] = {["Magic Evasion Bonus"] = 6,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Magic Accuracy Bonus"] = 6,},
			[45] = {["Elemental Magic Skill"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Dark Magic Skill"] = 5,},
			[80] = {["Magic Burst Damage"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["New Spells"] = {'Fire VI', 'Blizzard VI', 'Aero VI', 'Stone VI', 'Thunder VI', 'Water VI',},},
			[125] = {["Magic Damage Bonus"] = 5,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Elemental Celerity Effect"] = 2,},
			[180] = {["Magic Defense Bonus"] = 3,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Magic Attack Bonus"] = 11,},
			[245] = {["Magic Evasion Bonus"] = 9,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Magic Accuracy Bonus"] = 9,},
			[320] = {["Elemental Magic Skill"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Dark Magic Skill"] = 8,},
			[405] = {["Magic Burst Damage"] = 5,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Magic Damage Bonus"] = 5,},
			[500] = {["Superior"] = 3,},
			[500] = {["Elemental Celerity Effect"] = 2,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["New Spell"] = 'Aspir III',},
			[605] = {["Magic Defense Bonus"] = 4,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Magic Attack Bonus"] = 14,},
			[720] = {["Magic Evasion Bonus"] = 12,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Magic Accuracy Bonus"] = 12,},
			[845] = {["Elemental Magic Skill"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Dark Magic Skill"] = 10,},
			[980] = {["Magic Burst Damage"] = 6,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Magic Damage Bonus"] = 6,},
			[1125] = {["Elemental Celerity Effect"] = 2,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["New Spell"] = 'Death',},
			[1280] = {["Magic Defense Bonus"] = 5,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Magic Attack Bonus"] = 18,},
			[1445] = {["Magic Evasion Bonus"] = 15,},
			[1530] = {["Magic Accuracy Bonus"] = 15,},
			[1620] = {["Elemental Magic Skill"] = 13,},
			[1710] = {["Dark Magic Skill"] = 13,},
			[1805] = {["Magic Burst Damage"] = 7,},
			[1900] = {["Magic Damage Bonus"] = 7,},
			[2000] = {["Elemental Celerity Bonus"] = 2,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['RDM'] = {
		['Gifts'] = {
			[5] = {["Magic Defense Bonus"] = 4,["Capacity Point Bonus"] = 5,},
			[10] = {["Magic Attack Bonus"] = 4,},
			[20] = {["Magic Evasion Bonus"] = 8,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Magic Accuracy Bonus"] = 10,},
			[45] = {["Physical Accuracy Bonus"] = 3,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Enfeebling Magic Skill"] = 5,},
			[80] = {["Enhancing Magic Skill"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["New Spells"] = {'Fire V', 'Blizzard V', 'Aero V', 'Stone V', 'Thunder V', 'Water V',},},
			[125] = {["Enspell Damage"] = 5,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Fast Cast Effect"] = 2,},
			[180] = {["Magic Defense Bonus"] = 6,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Magic Attack Bonus"] = 6,},
			[245] = {["Magic Evasion Bonus"] = 12,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Magic Accuracy Bonus"] = 15,},
			[320] = {["Physical Accuracy Bonus"] = 5,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Enfeebling Magic Bonus"] = 8,},
			[405] = {["Enhancing Magic Skill"] = 8,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Enspell Damage"] = 5,},
			[500] = {["Superior"] = 3,},
			[500] = {["Fast Cast Effect"] = 2,},
			[550] = {["New Spells"] = {'Addle II', 'Distract III', 'Frazzle III',},},
			[545] = {["Capacity Point Bonus"] = 23,},
			[605] = {["Magic Defense Bonus"] = 8,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Magic Attack Bonus"] = 8,},
			[720] = {["Magic Evasion Bonus"] = 16,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Magic Accuracy Bonus"] = 20,},
			[845] = {["Physical Accuracy Bonus"] = 6,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Enfeebling Magic Skill"] = 10,},
			[980] = {["Enhancing Magic Skill"] = 10,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Enspell Damage"] = 5,},
			[1125] = {["Fast Cast Effect"] = 2,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["New Spells"] = {'Refresh III', 'Temper II', },},
			[1280] = {["Magic Defense Bonus"] = 10,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Magic Attack Bonus"] = 10,},
			[1445] = {["Magic Evasion Bonus"] = 20,},
			[1530] = {["Magic Accuracy Bonus"] = 25,},
			[1620] = {["Physical Accuracy Bonus"] = 8,},
			[1710] = {["Enfeebling Magic Skill"] = 13,},
			[1805] = {["Enhancing Magic Skill"] = 13,},
			[1900] = {["Enspell Damage"] = 5,},
			[2000] = {["Fast Cast Effect"] = 2,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['THF'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 4,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 7,},
			[20] = {["Physical Evasion Bonus"] = 10,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 5,},
			[45] = {["Magic Evasion Bonus"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Accuracy Bonus"] = 5,},
			[80] = {["\"Treasure Hunter\" Bonus"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["Maximum Treasure Hunter Value"] = 1,},
			[125] = {["Triple Attack Chance"] = 2,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Critical Damage Bonus"] = 2,},
			[180] = {["Physical Defense Bonus"] = 6,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 11,},
			[245] = {["Physical Evasion Bonus"] = 15,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 8,},
			[320] = {["Magic Evasion Bonus"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Accuracy Bonus"] = 8,},
			[405] = {["\"Treasure Hunter\" Bonus"] = 5,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Triple Attack Chance"] = 2,},
			[500] = {["Superior"] = 3,},
			[500] = {["Critical Damage Bonus"] = 2,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Dual Wield Effect"] = 5,},
			[605] = {["Physical Defense Bonus"] = 8,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 14,},
			[720] = {["Physical Evasion Bonus"] = 20,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 10,},
			[845] = {["Magic Evasion Bonus"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Accuracy Bonus"] = 10,},
			[980] = {["\"Treasure Hunter\" Bonus"] = 6,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Triple Attack Chance"] = 2,},
			[1125] = {["Critical Damage Bonus"] = 2,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Maximum Treasure Hunter Value"] = 1,},
			[1280] = {["Physical Defense Bonus"] = 10,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 18,},
			[1445] = {["Physical Evasion Bonus"] = 25,},
			[1530] = {["Physical Accuracy Bonus"] = 13,},
			[1620] = {["Magic Evasion Bonus"] = 13,},
			[1710] = {["Magic Accuracy Bonus"] = 13,},
			[1805] = {["\"Treasure Hunter\" Bonus"] = 7,},
			[1900] = {["Triple Attack Chance"] = 2,},
			[2000] = {["Critical Damage Bonus"] = 2,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['PLD'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 15,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 4,},
			[20] = {["Physical Evasion Bonus"] = 3,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 4,},
			[45] = {["Magic Evasion Bonus"] = 6,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Accuracy Bonus"] = 6,},
			[80] = {["Divine Magic Skill"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["New Spell"] = 'Enlight II',},
			[125] = {["Shield Mastery Effect"] = 3,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Critical Defense Bonus"] = 2,},
			[180] = {["Physical Defense Bonus"] = 23,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 6,},
			[245] = {["Physical Evasion Bonus"] = 5,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 6,},
			[320] = {["Magic Evasion Bonus"] = 9,},
			[355] = {["Capacity Points Bonus"] = 19,},
			[360] = {["Magic Accuracy Bonus"] = 9,},
			[405] = {["Divine Magic Skill"] = 8,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Shield Mastery Effect"] = 3,},
			[500] = {["Superior"] = 3,},
			[500] = {["Critical Defense Bonus"] = 2,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Protect Effect"] = 10,},
			[605] = {["Physical Defense Bonus"] = 30,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 8,},
			[720] = {["Physical Evasion Bonus"] = 6,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 8,},
			[845] = {["Magic Evasion Bonus"] = 12,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Accuracy Bonus"] = 12,},
			[980] = {["Divine Magic Skill"] = 10,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Shield Mastery Effect"] = 4,},
			[1125] = {["Critical Defense Bonus"] = 2,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Reprisal Effect"] = 20,},
			[1280] = {["Physical Defense Bonus"] = 38,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 10,},
			[1445] = {["Physical Evasion Bonus"] = 8,},
			[1530] = {["Physical Accuracy Bonus"] = 10,},
			[1620] = {["Magic Evasion Bonus"] = 15,},
			[1710] = {["Magic Accuracy Bonus"] = 15,},
			[1805] = {["Divine Magic Skill"] = 13,},
			[1900] = {["Shield Mastery Effect"] = 5,},
			[2000] = {["Critical Defense Bonus"] = 2,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['DRK'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 4,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 15,},
			[20] = {["Physical Evasion Bonus"] = 3,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 3,},
			[45] = {["Magic Evasion Bonus"] = 6,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Accuracy Bonus"] = 6,},
			[80] = {["Dark Magic Skill"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["New Spell"] = 'Endark II',},
			[125] = {["Critical Damage Bonus"] = 2,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Weapon Skill Damage"] = 2,},
			[180] = {["Physical Defense Bonus"] = 6,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 23,},
			[245] = {["Physical Evasion Bonus"] = 5,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 5,},
			[320] = {["Magic Evasion Bonus"] = 9,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Accuracy Bonus"] = 9,},
			[405] = {["Dark Magic Skill"] = 8,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Critical Damage Bonus"] = 2,},
			[500] = {["Superior"] = 3,},
			[500] = {["Weapon Skill Damage"] = 2,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["New Spell"] = 'Drain III',},
			[605] = {["Physical Defense Bonus"] = 8,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 30,},
			[720] = {["Physical Evasion Bonus"] = 6,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 6,},
			[845] = {["Magic Evasion Bonus"] = 6,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Accuracy Bonus"] = 12,},
			[980] = {["Dark Magic Skill"] = 10,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Critical Damage Dealt"] = 2,},
			[1125] = {["Weapon Skill Damage"] = 2,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Dread Spikes Effect"] = 20,},
			[1280] = {["Physical Defense Bonus"] = 10,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 38,},
			[1445] = {["Physical Evasion Bonus"] = 8,},
			[1530] = {["Physical Accuracy Bonus"] = 8,},
			[1620] = {["Magic Evasion Bonus"] = 15,},
			[1710] = {["Magic Accuracy Bonus"] = 15,},
			[1805] = {["Dark Magic Skill"] = 13,},
			[1900] = {["Critical Damage Bonus"] = 2,},
			[2000] = {["Weapon Skill Damage"] = 2,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['BST'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 10,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 10,},
			[20] = {["Physical Evasion Bonus"] = 5,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 5,},
			[45] = {["Magic Evasion Bonus"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Accuracy Bonus"] = 5,},
			[80] = {["Familiar Phys. Atk. and Def. Bonus"] = 15,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["Sic and Ready Recast Time"] = 5,},
			[125] = {["Familiar Phys. Acc. and Eva. Bonus"] = 10,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Fencer Effect	Increase"] = 50,},
			[180] = {["Physical Defense Bonus"] = 15,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 15,},
			[245] = {["Physical Evasion Bonus"] = 8,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 8,},
			[320] = {["Magic Evasion Bonus"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Accuracy Bonus"] = 8,},
			[405] = {["Familiar Phys. Atk. and Def. Bonus"] = 23,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Familiar Phys. Acc. and Eva. Bonus"] = 15,},
			[500] = {["Superior"] = 3,},
			[500] = {["Fencer Effect	Increases"] = 50,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Pet Attribute Bonus"] = 8,},
			[605] = {["Physical Defense Bonus"] = 20,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 20,},
			[720] = {["Physical Evasion Bonus"] = 10,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 10,},
			[845] = {["Magic Evasion Bonus"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Accuracy Bonus"] = 10,},
			[980] = {["Familiar Phys. Atk. and Def. Bonus"] = 30,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Familiar Phys. Acc. and Eva. Bonus"] = 20,},
			[1125] = {["Fencer Effect"] = 60,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Familiar TP Bonus"] = 40,},
			[1280] = {["Physical Defense Bonus"] = 25,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 25,},
			[1445] = {["Physical Evasion Bonus"] = 13,},
			[1530] = {["Physical Accuracy Bonus"] = 13,},
			[1620] = {["Magic Evasion Bonus"] = 13,},
			[1710] = {["Magic Accuracy Bonus"] = 13,},
			[1805] = {["Familiar Phys. Atk. and Def. Bonus"] = 38,},
			[1900] = {["Familiar Phys. Acc. and Eva. Bonus"] = 25,},
			[2000] = {["Fencer Effect"] = 70,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['BRD'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 3,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Evasion Bonus"] = 3,},
			[20] = {["Physical Accuracy Bonus"] = 2,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Magic Defense Bonus"] = 3,},
			[45] = {["Magic Evasion Bonus"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Accuracy Bonus"] = 5,},
			[80] = {["Singing Skill Bonus"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["New Songs"] = {'Fire Threnody II', 'Ice Threnody II', 'Wind Threnody II', 'Earth Threnody II', 'Lightning Threnody II', 'Water Threnody II', 'Light Threnody II', 'Dark Threnody II',},},
			[125] = {["String Instrument Skill"] = 5,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Wind Instrument Skill"] = 5,},
			[180] = {["Physical Defense Bonus"] = 5,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Evasion Bonus"] = 5,},
			[245] = {["Physical Accuracy Bonus"] = 5,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Magic Defense Bonus"] = 3,},
			[320] = {["Magic Evasion Bonus"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Accuracy Bonus"] = 8,},
			[405] = {["Singing Skill Bonus"] = 8,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["String Instrument Skill"] = 8,},
			[500] = {["Superior"] = 3,},
			[500] = {["Wind Instrument Skill"] = 8,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Song Spellcasting Time"] = 5,},
			[605] = {["Physical Defense Bonus"] = 6,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Evasion Bonus"] = 6,},
			[720] = {["Physical Accuracy Bonus"] = 6,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Magic Defense Bonus"] = 4,},
			[845] = {["Magic Evasion Bonus"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Accuracy Bonus"] = 10,},
			[980] = {["Singing Skill Bonus"] = 10,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["String Instrument Skill"] = 10,},
			[1125] = {["Wind Instrument Skill"] = 10,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Song Effect Duration"] = 5,},
			[1280] = {["Physical Defense Bonus"] = 8,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Evasion Bonus"] = 8,},
			[1445] = {["Physical Accuracy Bonus"] = 8,},
			[1530] = {["Magic Defense Bonus"] = 5,},
			[1620] = {["Magic Evasion Bonus"] = 13,},
			[1710] = {["Magic Accuracy Bonus"] = 13,},
			[1805] = {["Singing Skill Bonus"] = 13,},
			[1900] = {["String Instrument Skill"] = 13,},
			[2000] = {["Wind Instrument Skill"] = 13,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['RNG'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 3,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 10,},
			[20] = {["Physical Evasion Bonus"] = 2,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 10,},
			[45] = {["Magic Evasion Bonus"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Accuracy Bonus"] = 5,},
			[80] = {["Conserve TP Effect Bonus"] = 3,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["Velocity Shot Effect"] = 5,},
			[125] = {["True Shot Effect"] = 2,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Dead Aim Effect"] = 2,},
			[180] = {["Physical Defense Bonus"] = 5,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 15,},
			[245] = {["Physical Evasion Bonus"] = 3,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 15,},
			[320] = {["Magic Evasion Bonus"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Accuracy Bonus"] = 8,},
			[405] = {["Conserve TP Effect Bonus"] = 3,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["True Shot Effect"] = 2,},
			[500] = {["Superior"] = 3,},
			[500] = {["Dead Aim Effect"] = 2,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Barrage Effect"] = 1,},
			[605] = {["Physical Defense Bonus"] = 6,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 20,},
			[720] = {["Physical Evasion Bonus"] = 4,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 20,},
			[845] = {["Magic Evasion Bonus"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Accuracy Bonus"] = 10,},
			[980] = {["Conserve TP Effect Bonus"] = 4,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["True Shot Effect"] = 2,},
			[1125] = {["Dead Aim Effect"] = 2,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Velocity Shot Effect"] = 5,},
			[1280] = {["Physical Defense Bonus"] = 8,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 25,},
			[1445] = {["Physical Evasion Bonus"] = 5,},
			[1530] = {["Physical Accuracy Bonus"] = 25,},
			[1620] = {["Magic Evasion Bonus"] = 13,},
			[1710] = {["Magic Accuracy Bonus"] = 13,},
			[1805] = {["Conserve TP Effect Bonus"] = 5,},
			[1900] = {["True Shot Effect"] = 2,},
		},
	},
	['SAM'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 10,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 10,},
			[20] = {["Physical Evasion Bonus"] = 5,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 5,},
			[45] = {["Magic Evasion Bonus"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Accuracy Bonus"] = 5,},
			[80] = {["Zanshin Effect Bonus"] = 2,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["Hasso and Seigan Effect"] = 5,},
			[125] = {["Store TP Effect"] = 2,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Skillchain Bonus"] = 2,},
			[180] = {["Physical Defense Bonus"] = 15,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 15,},
			[245] = {["Physical Evasion Bonus"] = 8,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 8,},
			[320] = {["Magic Evasion Bonus"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Accuracy Bonus"] = 8,},
			[405] = {["Zanshin Chance Bonus"] = 2,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Store TP Effect"] = 2,},
			[500] = {["Superior"] = 3,},
			[500] = {["Skillchain Bonus"] = 2,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Third Eye Effect"] = 1,},
			[605] = {["Physical Defense Bonus"] = 20,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 20,},
			[720] = {["Physical Evasion Bonus"] = 10,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 10,},
			[845] = {["Magic Evasion Bonus"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Accuracy Bonus"] = 10,},
			[980] = {["Zanshin Chance Bonus"] = 3,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Store TP Effect"] = 2,},
			[1125] = {["Skillchain Bonus"] = 2,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Hasso and Seigan Effect"] = 5,},
			[1280] = {["Physical Defense Bonus"] = 25,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 25,},
			[1445] = {["Physical Evasion Bonus"] = 13,},
			[1530] = {["Physical Accuracy Bonus"] = 13,},
			[1620] = {["Magic Evasion Bonus"] = 13,},
			[1710] = {["Magic Accuracy Bonus"] = 13,},
			[1805] = {["Zanshin Chance Bonus"] = 3,},
			[1900] = {["Store TP Effect"] = 2,},
			[2000] = {["Skillchain Bonus"] = 2,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['NIN'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 8,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 10,},
			[20] = {["Physical Evasion Bonus"] = 9,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 8,},
			[45] = {["Magic Attack Bonus"] = 4,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Evasion Bonus"] = 7,},
			[80] = {["Magic Accuracy Bonus"] = 7,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[125] = {["Ninjutsu Skill Bonus"] = 5,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Daken Effect"] = 2,},
			[180] = {["Physical Defense Bonus"] = 12,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 15,},
			[245] = {["Physical Evasion Bonus"] = 14,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 12,},
			[320] = {["Magic Attack Bonus"] = 6,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Evasion Bonus"] = 11,},
			[405] = {["Magic Accuracy Bonus"] = 11,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Ninjutsu Skill Bonus"] = 8,},
			[500] = {["Superior"] = 3,},
			[500] = {["Daken Effect"] = 3,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Ninjutsu Effect Duration"] = 10,},
			[605] = {["Physical Defense Bonus"] = 16,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 20,},
			[720] = {["Physical Evasion Bonus"] = 18,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 16,},
			[845] = {["Magic Attack Bonus"] = 8,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Evasion Bonus"] = 14,},
			[980] = {["Magic Accuracy Bonus"] = 14,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Ninjutsu Skill Bonus"] = 10,},
			[1125] = {["Daken Effect"] = 4,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Weapon Skill Damage"] = 5,},
			[1280] = {["Physical Defense Bonus"] = 20,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 25,},
			[1445] = {["Physical Evasion Bonus"] = 23,},
			[1530] = {["Physical Accuracy Bonus"] = 20,},
			[1620] = {["Magic Attack Bonus"] = 10,},
			[1710] = {["Magic Evasion Bonus"] = 18,},
			[1805] = {["Magic Accuracy Bonus"] = 18,},
			[1900] = {["Ninjutsu Skill Bonus"] = 13,},
			[2000] = {["Daken Effect"] = 5,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['DRG'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 10,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 10,},
			[20] = {["Physical Evasion Bonus"] = 5,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 9,},
			[45] = {["Magic Evasion Bonus"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Accuracy Bonus"] = 5,},
			[80] = {["Critical Damage Bonus"] = 2,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["Wyvern Attribute Increase Effect"] = 1,},
			[125] = {["Wyvern Phys. Acc. and Eva. Bonus"] = 10,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Wyvern Mag. Acc. and Eva. Bonus"] = 10,},
			[180] = {["Physical Defense Bonus"] = 15,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 15,},
			[245] = {["Physical Evasion Bonus"] = 8,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 14,},
			[320] = {["Magic Evasion Bonus"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Accuracy Bonus"] = 8,},
			[405] = {["Critical Damage Bonus"] = 2,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Wyvern Phys. Acc. and Eva. Bonus"] = 15,},
			[500] = {["Superior"] = 3,},
			[500] = {["Wyvern Mag. Acc. and Eva. Bonus"] = 10,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Restoring/Smiting Breath Delay"] = 10,},
			[605] = {["Physical Defense Bonus"] = 20,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 20,},
			[720] = {["Physical Evasion Bonus"] = 10,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 18,},
			[845] = {["Magic Evasion Bonus"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Accuracy Bonus"] = 10,},
			[980] = {["Critical Dmaage Bonus"] = 2,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Wyvern Phys. Acc. and Eva. Bonus"] = 20,},
			[1125] = {["Wyvern Mag. Acc. and Eva. Bonus"] = 20,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Wyvern Attribute Increase Effect"] = 2,},
			[1280] = {["Physical Defense Bonus"] = 25,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 25,},
			[1445] = {["Physical Evasion Bonus"] = 13,},
			[1530] = {["Physical Accuracy Bonus"] = 23,},
			[1620] = {["Magic Evasion Bonus"] = 13,},
			[1710] = {["Magic Accuracy Bonus"] = 13,},
			[1805] = {["Critical Damage Bonus"] = 2,},
			[1900] = {["Wyvern Phys. Acc. and Eva. Bonus"] = 25,},
			[2000] = {["Wyvern Mag. Acc. and Eva. Bonus"] = 25,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['SMN'] = {
		['Gifts'] = {
			[5] = {["Magic Defense Bonus"] = 3,["Capacity Point Bonus"] = 5,},
			[10] = {["Magic Evasion Bonus"] = 3,},
			[20] = {["Physical Defense Bonus"] = 3,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Evasion Bonus"] = 3,},
			[45] = {["Spirit and Avatar Physical Attack and Defense Bonus"] = 15,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Spirit and Avatar Physical Accuracy and Physical Evasion Bonus"] = 10,},
			[80] = {["Spirit and Avatar Magic Attack and Defense Bonus"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["Blood Pact Recast Time"] = 5,},
			[125] = {["Spirit and Avatar Magic Accuracy and Evasion Bonus"] = 10,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Summoning Magic Skill"] = 5,},
			[180] = {["Magic Defense Bonus"] = 5,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Magic Evasion Bonus"] = 5,},
			[245] = {["Physical Defense Bonus"] = 5,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Evasion Bonus"] = 5,},
			[320] = {["Spirit and Avatar Physical Attack and Defense Bonus"] = 23,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Spirit and Avatar Physical Accuracy and Physical Evasion Bonus"] = 15,},
			[405] = {["Spirit and Avatar Magic Attack and Defense Bonus"] = 8,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Spirit and Avatar Magic Accuracy and Evasion Bonus"] = 15,},
			[500] = {["Superior"] = 3,},
			[500] = {["Summoning Magic Skill"] = 8,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Avatar\'s Favor Effect"] = 1,},
			[605] = {["Magic Defense Bonus"] = 6,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Magic Evasion Bonus"] = 6,},
			[720] = {["Physical Defense Bonus"] = 6,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Evasion Bonus"] = 6,},
			[845] = {["Spirit and Avatar Physical Attack and Defense Bonus"] = 30,},
			[905] = {["Spirit and Avatar Physical Accuracy and Physical Evasion Bonus"] = 20,},
			[910] = {["Capacity Point Bonus"] = 29,},
			[980] = {["Spirit and Avatar Magic Attack and Defense Bonus"] = 10,},
			[1045] = {["Spirit and Avatar Magic Accuracy and Evasion Bonus"] = 20,},
			[1050] = {["Capacity Point Bonus"] = 31,},
			[1125] = {["Summoning Magic Skill"] = 10,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Blood Pact Recast Time"] = 5,},
			[1280] = {["Magic Defense Bonus"] = 8,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Magic Evasion Bonus"] = 8,},
			[1445] = {["Physical Defense Bonus"] = 8,},
			[1530] = {["Physical Evasion Bonus"] = 8,},
			[1620] = {["Spirit and Avatar Physical Attack and Defense Bonus"] = 38,},
			[1710] = {["Spirit and Avatar Physical Accuracy and Physical Evasion Bonus"] = 25,},
			[1805] = {["Spirit and Avatar Magic Attack and Defense Bonus"] = 13,},
			[1900] = {["Spirit and Avatar Magic Accuracy and Evasion Bonus"] = 25,},
			[2000] = {["Summoning Magic Skill"] = 13,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['BLU'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 10,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 10,},
			[20] = {["Physical Evasion Bonus"] = 5,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 5,},
			[45] = {["Magic Defense Bonus"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Attack Bonus"] = 5,},
			[80] = {["Magic Evasion Bonus"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["Job Trait Bonus"] = 1,},
			[125] = {["Magic Accuracy Bonus"] = 5,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Blue Magic Skill"] = 5,},
			[180] = {["Physical Defense Bonus"] = 15,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 15,},
			[245] = {["Physical Evasion Bonus"] = 8,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 8,},
			[320] = {["Magic Defense Bonus"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Attack Bonus"] = 8,},
			[405] = {["Magic Evasion Bonus"] = 8,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Magic Accuracy Bonus"] = 8,},
			[500] = {["Superior"] = 3,},
			[500] = {["Blue Magic Skill"] = 8,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Blue Magic Effect"] = 5,},
			[605] = {["Physical Defense Bonus"] = 20,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 20,},
			[720] = {["Physical Evasion Bonus"] = 10,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 10,},
			[845] = {["Magic Defense Bonus"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Attack Bonus"] = 10,},
			[980] = {["Magic Evasion Bonus"] = 10,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Magic Accuracy Bonus"] = 10,},
			[1125] = {["Blue Magic Skill"] = 10,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Job Trait Bonus"] = 1,},
			[1280] = {["Physical Defense Bonus"] = 25,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 25,},
			[1445] = {["Physical Evasion Bonus"] = 13,},
			[1530] = {["Physical Accuracy Bonus"] = 13,},
			[1620] = {["Magic Defense Bonus"] = 13,},
			[1710] = {["Magic Attack Bonus"] = 13,},
			[1805] = {["Magic Evasion Bonus"] = 13,},
			[1900] = {["Magic Accuracy Bonus"] = 13,},
			[2000] = {["Blue Magic Skill"] = 13,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['COR'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 3,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 5,},
			[20] = {["Physical Evasion Bonus"] = 3,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 5,},
			[45] = {["Magic Attack Bonus"] = 2,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Evasion Bonus"] = 5,},
			[80] = {["Magic Accuracy Bonus"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["Snapshot Effect"] = 5,},
			[125] = {["Reduced Ammunition Consumption"] = 2,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["True Shot Effect"] = 2,},
			[180] = {["Physical Defense Bonus"] = 5,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 8,},
			[245] = {["Physical Evasion Bonus"] = 5,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 8,},
			[320] = {["Magic Attack Bonus"] = 3,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Evasion Bonus"] = 8,},
			[405] = {["Magic Accuracy Bonus"] = 8,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Reduced Ammunition Consumption"] = 2,},
			[500] = {["Superior"] = 3,},
			[500] = {["True Shot Effect"] = 2,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Quick Draw Delay"] = 10,},
			[605] = {["Physical Defense Bonus"] = 6,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 10,},
			[720] = {["Physical Evasion Bonus"] = 6,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 10,},
			[845] = {["Magic Attack Bonus"] = 4,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Evasion Bonus"] = 10,},
			[980] = {["Magic Accuracy Bonus"] = 10,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Reduced Ammunition Consumption"] = 2,},
			[1125] = {["True Shot Effect"] = 2,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Snapshot Effect"] = 5,},
			[1280] = {["Physical Defense Bonus"] = 8,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 13,},
			[1445] = {["Physical Evasion Bonus"] = 8,},
			[1530] = {["Physical Accuracy Bonus"] = 13,},
			[1620] = {["Magic Attack Bonus"] = 5,},
			[1710] = {["Magic Evasion Bonus"] = 13,},
			[1805] = {["Magic Accuracy Bonus"] = 13,},
			[1900] = {["Reduced Ammunition Consumption"] = 2,},
			[2000] = {["True Shot Effect"] = 2,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['PUP'] = {
		['Gifts'] = {
			[5] = {["Physical Attack Bonus"] = 6,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Evasion Bonus"] = 8,},
			[20] = {["Physical Accuracy Bonus"] = 7,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Magic Evasion Bonus"] = 5,},
			[45] = {["Magic Accuracy Bonus"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Automaton Physical Attack and Defense Bonus"] = 15,},
			[80] = {["Automaton Physical Accuracy and Physical Evasion Bonus"] = 10,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["Automaton Elemental Capacity Bonus"] = 2,},
			[125] = {["Automaton Mag. Atk. and Def. Bonus"] = 5,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Mag. Acc. and Eva. Bonus"] = 10,},
			[180] = {["Physical Attack Bonus"] = 9,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Evasion Bonus"] = 12,},
			[245] = {["Physical Accuracy Bonus"] = 11,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Magic Evasion Bonus"] = 8,},
			[320] = {["Magic Accuracy Bonus"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Automaton Physical Attack and Defense Bonus"] = 23,},
			[405] = {["Automaton Physical Accuracy and Physical Evasion Bonus"] = 15,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Automaton Mag. Atk. and Def. Bonus"] = 8,},
			[500] = {["Superior"] = 3,},
			[500] = {["Mag. Acc. and Eva. Bonus"] = 15,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Martial Arts Effect"] = 5,},
			[605] = {["Physical Attack Bonus"] = 12,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Evasion Bonus"] = 16,},
			[720] = {["Physical Accuracy Bonus"] = 14,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Magic Evasion Bonus"] = 10,},
			[845] = {["Magic Accuracy bonus"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Automaton Physical Attack and Defense Bonus"] = 30,},
			[980] = {["Automaton Physical Accuracy and Physical Evasion Bonus"] = 20,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Automaton Mag. Atk. and Def. Bonus"] = 10,},
			[1125] = {["Mag. Acc. and Eva. Bonus"] = 20,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Automaton Elemental Capacity Bonus"] = 2,},
			[1280] = {["Physical Attack Bonus"] = 15,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Evasion Bonus"] = 20,},
			[1445] = {["Physical Accuracy Bonus"] = 18,},
			[1530] = {["Magic Evasion Bonus"] = 13,},
			[1620] = {["Magic Accuracy Bonus"] = 13,},
			[1710] = {["Automaton Physical Attack and Defense Bonus"] = 38,},
			[1850] = {["Automaton Physical Accuracy and Physical Evasion Bonus"] = 25,},
			[1900] = {["Automaton Mag. Atk. and Def. Bonus"] = 13,},
			[2000] = {["Mag. Acc. and Eva. Bonus"] = 25,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['DNC'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 6,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 6,},
			[20] = {["Physical Evasion Bonus"] = 9,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 9,},
			[45] = {["Magic Evasion Bonus"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Accuracy Bonus"] = 5,},
			[80] = {["\"Subtle Blow\" Effect Bonus"] = 3,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["Maximum Finishing Moves Bonus"] = 2,},
			[125] = {["Critical Damage Bonus"] = 2,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Skillchain Bonus"] = 2,},
			[180] = {["Physical Defense Bonus"] = 9,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 9,},
			[245] = {["Physical Evasion Bonus"] = 14,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 14,},
			[320] = {["Magic Evasion Bonus"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Accuracy Bonus"] = 8,},
			[405] = {["\"Subtle Blow\" Effect Bonus"] = 3,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Critical Damage Bonus"] = 2,},
			[500] = {["Superior"] = 3,},
			[500] = {["Skillchain Bonus"] = 2,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Dual Wield Effect"] = 5,},
			[605] = {["Physical Defense Bonus"] = 12,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 12,},
			[720] = {["Physical Evasion Bonus"] = 18,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 18,},
			[845] = {["Magic Evasion Bonus"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Accuracy Bonus"] = 10,},
			[980] = {["\"Subtle Blow\" Effect Bonus"] = 3,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Critical Damage Bonus"] = 2,},
			[1125] = {["Skillchain Bonus"] = 2,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Maximum Finishing Moves Bonus"] = 2,},
			[1280] = {["Physical Defense Bonus"] = 15,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 15,},
			[1445] = {["Physical Evasion Bonus"] = 23,},
			[1530] = {["Physical Accuracy Bonus"] = 23,},
			[1620] = {["Magic Evasion Bonus"] = 13,},
			[1710] = {["Magic Accuracy Bonus"] = 13,},
			[1805] = {["\"Subtle Blow\" Effect Bonus"] = 4,},
			[1900] = {["Critical Damage Bonus"] = 2,},
			[2000] = {["Skillchain Bonus"] = 2,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['SCH'] = {
		['Gifts'] = {
			[5] = {["Magic Defense Bonus"] = 3,["Capacity Point Bonus"] = 5,},
			[10] = {["Magic Attack Bonus"] = 5,},
			[20] = {["Magic Evasion Bonus"] = 6,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Magic Accuracy Bonus"] = 6,},
			[45] = {["Dark Magic Skill"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Enhancing Magic Skill"] = 5,},
			[80] = {["Elemental Magic Skill"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["New Spells"] = {'Sandstorm II', 'Rainstorm II', 'Windstorm II', 'Firestorm II', 'Hailstorm II', 'Thunderstorm II', 'Aurorastorm II', 'Voidstorm II', },},
			[125] = {["Healing Magic Skill"] = 5,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Magic Burst Damage"] = 3,},
			[180] = {["Magic Defense Bonus"] = 5,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Magic Attack Bonus"] = 8,},
			[245] = {["Magic Evasion Bonus"] = 9,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Magic Accuracy Bonus"] = 9,},
			[320] = {["Dark Magic Skill"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Enhancing Magic Skill"] = 8,},
			[405] = {["Elemental Magic Skill"] = 8,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Healing Magic Skill"] = 8,},
			[500] = {["Superior"] = 3,},
			[500] = {["Magic Burst Damage"] = 3,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["Stratagem Recast Time"] = 15,},
			[605] = {["Magic Defense Bonus"] = 6,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Magic Attack Bonus"] = 10,},
			[720] = {["Magic Evasion Bonus"] = 12,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Magic Accuracy Bonus"] = 12,},
			[845] = {["Dark Magic Skill"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Enhancing Magic Skill"] = 10,},
			[980] = {["Elemental Magic Skill"] = 10,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Healing Magic Skill"] = 10,},
			[1125] = {["Magic Burst Damage"] = 3,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["New Spells"] = {'Geohelix II', 'Hydrohelix II', 'Anemohelix II', 'Pyrohelix II', 'Cryohelix II', 'Ionohelix II', 'Noctohelix II', 'Luminohelix II', },},
			[1280] = {["Magic Defense Bonus"] = 8,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Magic Attack Bonus"] = 13,},
			[1445] = {["Magic Evasion Bonus"] = 15,},
			[1530] = {["Magic Accuracy Bonus"] = 15,},
			[1620] = {["Dark Magic Skill"] = 13,},
			[1710] = {["Enhancing Magic Skill"] = 13,},
			[1805] = {["Elemental Magic Skill"] = 13,},
			[1900] = {["Healing Magic Skill"] = 13,},
			[2000] = {["Magic Burst Damage"] = 4,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['GEO'] = {
		['Gifts'] = {
			[5] = {["Magic Defense Bonus"] = 4,["Capacity Point Bonus"] = 5,},
			[10] = {["Magic Attack Bonus"] = 6,},
			[20] = {["Magic Evasion Bonus"] = 7,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Magic Accuracy Bonus"] = 7,},
			[45] = {["Geomancy Skill Bonus"] = 5,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Handbell Skill Bonus"] = 5,},
			[80] = {["Elemental Magic Skill"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["New Spells"] = {'Fire V', 'Blizzard V', 'Aero V', 'Stone V', 'Thunder V', 'Water V', },},
			[125] = {["Dark Magic Skill"] = 5,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Magic Damage Bonus"] = 3,},
			[180] = {["Magic Defense Bonus"] = 6,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Magic Attack Bonus"] = 9,},
			[245] = {["Magic Evasion Bonus"] = 11,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Magic Accuracy Bonus"] = 11,},
			[320] = {["Geomancy Skill Bonus"] = 8,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Handbell Skill Bonus"] = 8,},
			[405] = {["Elemental Magic Skill"] = 8,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Dark Magic Skill"] = 8,},
			[500] = {["Superior"] = 3,},
			[500] = {["Magic Damage Bonus"] = 3,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["New Spell"] = 'Aspir III',},
			[605] = {["Magic Defense Bonus"] = 8,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Magic Attack Bonus"] = 12,},
			[720] = {["Magic Evasion Bonus"] = 14,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Magic Accuracy Bonus"] = 14,},
			[845] = {["Geomancy Skill Bonus"] = 10,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Handbell Skill Bonus"] = 10,},
			[980] = {["Elemental Magic Skill"] = 10,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Dark Magic Skill"] = 10,},
			[1125] = {["Magic Damage Bonus"] = 3,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["New Spells"] = {'Fira III', 'Blizzara III', 'Aerora III', 'Stonera III', 'Thundara III', 'Watera III', },},
			[1280] = {["Magic Defense Bonus"] = 10,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Magic Attack Bonus"] = 15,},
			[1445] = {["Magic Evasion Bonus"] = 18,},
			[1530] = {["Magic Accuracy Bonus"] = 18,},
			[1620] = {["Geomancy Skill Bonus"] = 13,},
			[1710] = {["Handbell Skill Bonus"] = 13,},
			[1805] = {["Elemental Skill Bonus"] = 13,},
			[1900] = {["Dark Magic Skill"] = 13,},
			[2000] = {["Magic Damage Bonus"] = 4,},
			[2100] = {["★Master!"] = 15,},
		},
	},
	['RUN'] = {
		['Gifts'] = {
			[5] = {["Physical Defense Bonus"] = 5,["Capacity Point Bonus"] = 5,},
			[10] = {["Physical Attack Bonus"] = 7,},
			[20] = {["Physical Evasion Bonus"] = 8,},
			[25] = {["Capacity Point Bonus"] = 7,},
			[30] = {["Physical Accuracy Bonus"] = 8,},
			[45] = {["Magic Defense Bonus"] = 8,},
			[50] = {["Superior"] = 1,},
			[55] = {["Capacity Point Bonus"] = 9,},
			[60] = {["Magic Evasion Bonus"] = 10,},
			[80] = {["Magic Accuracy Bonus"] = 5,},
			[95] = {["Capacity Point Bonus"] = 11,},
			[100] = {["Superior"] = 2,},
			[100] = {["Enhancing Magic Received Duration"] = 10,},
			[125] = {["Enhancing Magic Skill"] = 5,},
			[145] = {["Capacity Point Bonus"] = 13,},
			[150] = {["Inquartata Effect"] = 2,},
			[180] = {["Physical Defense Bonus"] = 8,},
			[205] = {["Capacity Point Bonus"] = 15,},
			[210] = {["Physical Attack Bonus"] = 11,},
			[245] = {["Physical Evasion Bonus"] = 12,},
			[275] = {["Capacity Point Bonus"] = 17,},
			[280] = {["Physical Accuracy Bonus"] = 12,},
			[320] = {["Magic Defense Bonus"] = 12,},
			[355] = {["Capacity Point Bonus"] = 19,},
			[360] = {["Magic Evasion Bonus"] = 15,},
			[405] = {["Magic Accuracy Bonus"] = 8,},
			[445] = {["Capacity Point Bonus"] = 21,},
			[450] = {["Enhancing Magic Skill"] = 8,},
			[500] = {["Superior"] = 3,},
			[500] = {["Inquartata Effect"] = 2,},
			[545] = {["Capacity Point Bonus"] = 23,},
			[550] = {["New Spell"] = 'Temper',},
			[605] = {["Physical Defense Bonus"] = 10,},
			[655] = {["Capacity Point Bonus"] = 25,},
			[660] = {["Physical Attack Bonus"] = 14,},
			[720] = {["Physical Evasion Bonus"] = 16,},
			[775] = {["Capacity Point Bonus"] = 27,},
			[780] = {["Physical Accuracy Bonus"] = 16,},
			[845] = {["Magic Defense Bonus"] = 16,},
			[905] = {["Capacity Point Bonus"] = 29,},
			[910] = {["Magic Evasion Bonus"] = 20,},
			[980] = {["Magic Accuracy Bonus"] = 10,},
			[1045] = {["Capacity Point Bonus"] = 31,},
			[1050] = {["Enhancing Magic Skill"] = 10,},
			[1125] = {["Inquartata Effect"] = 2,},
			[1195] = {["Capacity Point Bonus"] = 33,},
			[1200] = {["Enhancing Magic Received Duration"] = 10,},
			[1280] = {["Physical Defense Bonus"] = 13,},
			[1355] = {["Capacity Point Bonus"] = 35,},
			[1360] = {["Physical Attack Bonus"] = 18,},
			[1445] = {["Physical Evasion Bonus"] = 20,},
			[1530] = {["Physical Accuracy Bonus"] = 20,},
			[1620] = {["Magic Defense Bonus"] = 20,},
			[1710] = {["Magic Evasion Bonus"] = 25,},
			[1805] = {["Magic Accuracy Bonus"] = 13,},
			[1900] = {["Enhancing Magic Skill"] = 13,},
			[2000] = {["Inquartata Effect"] = 2,},
			[2100] = {["★Master!"] = 15,},
		},
	},
}