local sw_zones = {}

sw_zones.hp = S{
	"Southern San d'Oria",
	"Northern San d'Oria",
	"Port San d'Oria",
	"Bastok Mines",
	"Bastok Markets",
	"Port Bastok",
	"Metalworks",
	"Windurst Waters",
	"Windurst Walls",
	"Port Windurst",
	"Windurst Woods",
	"Ru'Lude Gardens",
	"Upper Jeuno",
	"Lower Jeuno",
	"Port Jeuno",
	"Kazham",
	"Mhaura",
	"Norg",
	"Rabao",
	"Selbina",
	"Western Adoulin",
	"Eastern Adoulin",
	"Ceizak Battlegrounds",
	"Foret de Hennetiel",
	"Morimar Basalt Fields",
	"Yorcia Weald",
	"Marjami Ravine",
	"Kamihr Drifts",
	"Yughott Grotto",
	"Palborough Mines",
	"Giddeus",
	"Fei'Yin",
	"Quicksand Caves",
	"Den of Rancor",
	"Castle Zvahl Keep",
	"Ru'Aun Gardens",
	"Tavnazian Safehold",
	"Aht Urhgan Whitegate",
	"Nashmau",
	"Southern San d'Oria [S]",
	"Bastok Markets [S]",
	"Windurst Waters [S]",
	"Upper Delkfutt's Tower",
	"The Shrine of Ru'Avitau",
	"Riverne - Site #B01",
	"Bhaflau Thickets",
	"Caedarva Mire",
	"Uleguerand Range",
	"Attohwa Chasm",
	"Pso'Xja",
	"Newton Movalpolos",
	"Riverne - Site #A01",
	"Al'Taieu",
	"Grand Palace of Hu'Xzoi",
	"The Garden of Ru'Hmet",
	"Mount Zhayolm",
	"Cape Teriggan",
	"The Boyahda Tree",
	"Ifrit's Cauldron",
	"Xarcabard [S]",
	"Leafallia",
	"Castle Zvahl Keep [S]",
	"Qufim Island",
	"Toraimarai Canal",
	"Ra'Kaznar Inner Court",
	"Misareaux Coast"
}

sw_zones.sg = S{
	"Northern San d'oria",
	"Bastok Mines",
	"Port Windurst",
	"Ru'Lude Gardens",
	"Tavnazian Safehold",
	"Aht Urhgan Whitegate",
	"Eastern Adoulin",
	"West Ronfaure",
	"Fort Ghelsba",
	"Bostaunieux Oubliette",
	"King Ranperre's Tomb",
	"La Theine Plateau",
	"Valkurm Dunes",
	"Konschtat Highlands",
	"Ordelle's Caves",
	"Gusgen Mines",
	"Carpenters' Landing",
	"Jugner Forest",
	"Batallia Downs",
	"Davoi",
	"The Eldieme Nercopolis",
	"North Gustaberg",
	"Zeruhn Mines",
	"Korroloka Tunnel",
	"Dangruf Wadi",
	"Pashhow Marshlands",
	"Rolanberry Fields",
	"Beadeaux",
	"Crawler's Nest",
	"West Sarutabaruta",
	"Toraimarai Canal",
	"Inner Horutoto Ruins",
	"Bibiki Bay",
	"Tahrongi Canyon",
	"Buburimu Peninsula",
	"Maze of Shakhrami",
	"Labyrinth of Onzozo",
	"Meriphataud Mountains",
	"Sauromugue Champaign",
	"Castle Oztroja",
	"Garlaige Citadel",
	"Beaucedine Glacier",
	"Ranguemont Pass",
	"Xarcabard",
	"Castle Zvahl Baileys",
	"Qufim Island",
	"Behemoth's Dominion",
	"Lower Delkfutt's Tower",
	"The Sanctuary of Zi'Tah",
	"Ro'Maeve",
	"Dragon's Aery",
	"Eastern Altepa Desert",
	"Western Altepa Desert",
	"Rabao",
	"Cape Teriggan",
	"Valley of Sorrows",
	"Kuftal Tunnel",
	"Gustav Tunnel",
	"Yuhtunga Jungle",
	"Sea Serpent Grotto",
	"Kazham",
	"Norg",
	"Yhoator Jungle",
	"Temple of Uggalepih",
	"Ifrit's Cauldron",
	"Ru'Aun Gardens",
	"Oldton Movalpolos",
	"Lufaise Meadows",
	"Misareaux Coast",
	"Phomiuna Aqueducts",
	"Sacrarium",
	"Wajaom Woodlands",
	"Mamook",
	"Aydeewa Subterrane",
	"Halvung",
	"Nashmau",
	"Arrapago Reef",
	"Caedarva Mire",
	"Southern San d'Oria [S]",
	"East Ronfaure [S]",
	"Jugner Forest [S]",
	"Batallia Downs [S]",
	"The Eldieme Necropolis [S]",
	"Bastok Markets [S]",
	"North Gustaberg [S]",
	"Grauberg [S]",
	"Vunkerl Inlet [S]",
	"Pashhow Marshlands [S]",
	"Rolanberry Fields [S]",
	"Crawlers' Nest [S]",
	"Windurst Waters [S]",
	"West Sarutabaruta [S]",
	"Fort Karugo-Narugo [S]",
	"Meriphataud Mountains [S]",
	"Sauromugue Champaign [S]",
	"Garlaige Citadel [S]",
	"Beaucedine Glacier [S]",
	"Castle Zvahl Baileys [S]"
}

return sw_zones