-- Generated by the Organizer Library (Sun Jul 14 22:30:59 2019)
return {
    [1]={
        ["log_name"]="founder's breastplate", 
        ["count"]=1, 
        ["id"]=27910, 
        ["name"]="found. breastplate", 
        ["augments"]={
            [1]="Accuracy+14", 
            [2]="Mag. Acc.+13", 
            [3]="Attack+14", 
            [4]="\"Mag.Atk.Bns.\"+14"
        }
    }, 
    [2]={
        ["log_name"]="sulevia's leggings +1", 
        ["id"]=25926, 
        ["name"]="sulev. leggings +1", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="jumalik mail", 
        ["count"]=1, 
        ["id"]=26972, 
        ["name"]="jumalik mail", 
        ["augments"]={
            [1]="HP+50", 
            [2]="Attack+13", 
            [3]="Enmity+7", 
            [4]="\"Refresh\"+1"
        }
    }, 
    [4]={
        ["log_name"]="sulevia's cuisses +1", 
        ["id"]=25859, 
        ["name"]="sulevi. cuisses +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="ishvara earring", 
        ["id"]=27537, 
        ["name"]="ishvara earring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="beatific earring", 
        ["id"]=10298, 
        ["name"]="beatific earring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="ochain", 
        ["id"]=16193, 
        ["name"]="ochain", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="jumalik helm", 
        ["count"]=1, 
        ["id"]=25603, 
        ["name"]="jumalik helm", 
        ["augments"]={
            [1]="MND+7", 
            [2]="\"Mag.Atk.Bns.\"+12", 
            [3]="Magic burst dmg.+7%"
        }
    }, 
    [9]={
        ["log_name"]="souveran handschuhs", 
        ["count"]=1, 
        ["id"]=27022, 
        ["name"]="souv. handschuhs", 
        ["augments"]={
            [1]="HP+50", 
            [2]="Shield skill +10", 
            [3]="Phys. dmg. taken -3"
        }
    }, 
    [10]={
        ["log_name"]="unmoving collar", 
        ["id"]=27508, 
        ["name"]="unmoving collar", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="founder's hose", 
        ["count"]=1, 
        ["id"]=28191, 
        ["name"]="founder's hose", 
        ["augments"]={
            [1]="MND+5", 
            [2]="Mag. Acc.+5", 
            [3]="Attack+7", 
            [4]="Breath dmg. taken -2%"
        }
    }, 
    [12]={
        ["log_name"]="weard mantle", 
        ["id"]=28623, 
        ["name"]="weard mantle", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="chozoron coselete", 
        ["id"]=26971, 
        ["name"]="chozor. coselete", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="souveran cuirass", 
        ["count"]=1, 
        ["id"]=26846, 
        ["name"]="souveran cuirass", 
        ["augments"]={
            [1]="HP+80", 
            [2]="Enmity+7", 
            [3]="Potency of \"Cure\" effect received +10%"
        }
    }, 
    [15]={
        ["log_name"]="odyssean cuisses", 
        ["count"]=1, 
        ["id"]=25840, 
        ["name"]="odyssean cuisses", 
        ["augments"]={
            [1]="\"Fast Cast\"+5"
        }
    }, 
    [16]={
        ["log_name"]="aegis", 
        ["id"]=11927, 
        ["name"]="aegis", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="amm greaves", 
        ["count"]=1, 
        ["id"]=27491, 
        ["name"]="amm greaves", 
        ["augments"]={
            [1]="HP+50", 
            [2]="VIT+10", 
            [3]="Accuracy+15", 
            [4]="Damage taken-2%"
        }
    }, 
    [18]={
        ["log_name"]="valorous hose", 
        ["count"]=1, 
        ["id"]=25841, 
        ["name"]="valor. hose", 
        ["augments"]={
            [1]="Accuracy+23", 
            [2]="Damage taken-4%", 
            [3]="AGI+6"
        }
    }, 
    [19]={
        ["log_name"]="fierabras's mantle", 
        ["id"]=11005, 
        ["name"]="fierabras's mantle", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="founder's corona", 
        ["count"]=1, 
        ["id"]=27764, 
        ["name"]="founder's corona", 
        ["augments"]={
            [1]="DEX+8", 
            [2]="Accuracy+15", 
            [3]="Mag. Acc.+14", 
            [4]="Magic dmg. taken -3%"
        }
    }, 
    [21]={
        ["log_name"]="creed baudrier", 
        ["id"]=11750, 
        ["name"]="creed baudrier", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="odyssean greaves", 
        ["count"]=1, 
        ["id"]=27494, 
        ["name"]="odyssean greaves", 
        ["augments"]={
            [1]="Accuracy+25 Attack+25", 
            [2]="STR+4", 
            [3]="Accuracy+7", 
            [4]="Attack+2"
        }
    }, 
    [23]={
        ["log_name"]="rudianos's mantle", 
        ["count"]=1, 
        ["id"]=26252, 
        ["name"]="rudianos's mantle", 
        ["augments"]={
            [1]="\"Fast Cast\"+10"
        }
    }, 
    [24]={
        ["log_name"]="subtlety spectacles", 
        ["id"]=27513, 
        ["name"]="subtlety spec.", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="sulevia's gauntlets +1", 
        ["id"]=25801, 
        ["name"]="sulev. gauntlets +1", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="thureous earring", 
        ["id"]=27546, 
        ["name"]="thureous earring", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="eschite gauntlets", 
        ["count"]=1, 
        ["id"]=27097, 
        ["name"]="eschite gauntlets", 
        ["augments"]={
            [1]="Mag. Evasion+15", 
            [2]="Spell interruption rate down +15%", 
            [3]="Enmity+7"
        }
    }, 
    [28]={
        ["log_name"]="coatl gorget +1", 
        ["id"]=28363, 
        ["name"]="coatl gorget +1", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="divine torque", 
        ["id"]=13152, 
        ["name"]="divine torque", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="asklepian belt", 
        ["id"]=26327, 
        ["name"]="asklepian belt", 
        ["count"]=1
    }
}