-- Generated by the Organizer Library (Sat Mar  6 14:37:10 2021)
return {
    [1]={
        ["log_name"]="ishvara earring", 
        ["id"]=27537, 
        ["name"]="ishvara earring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="founder's hose", 
        ["count"]=1, 
        ["id"]=28191, 
        ["name"]="founder's hose", 
        ["augments"]={
            [1]="MND+5", 
            [2]="Mag. Acc.+5", 
            [3]="Attack+7", 
            [4]="Breath dmg. taken -2%"
        }
    }, 
    [3]={
        ["log_name"]="flamma gambieras +2", 
        ["id"]=25953, 
        ["name"]="flam. gambieras +2", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="amm greaves", 
        ["count"]=1, 
        ["id"]=27491, 
        ["name"]="amm greaves", 
        ["augments"]={
            [1]="HP+50", 
            [2]="VIT+10", 
            [3]="Accuracy+15", 
            [4]="Damage taken-2%"
        }
    }, 
    [5]={
        ["log_name"]="odnowa earring", 
        ["id"]=27548, 
        ["name"]="odnowa earring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="founder's corona", 
        ["id"]=27764, 
        ["name"]="founder's corona", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="incanter's torque", 
        ["id"]=26016, 
        ["name"]="incanter's torque", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="enchanter earring +1", 
        ["id"]=28494, 
        ["name"]="enchntr. earring +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="eschite cuisses", 
        ["count"]=1, 
        ["id"]=27282, 
        ["name"]="eschite cuisses", 
        ["augments"]={
            [1]="\"Mag.Atk.Bns.\"+25", 
            [2]="\"Conserve MP\"+6", 
            [3]="\"Fast Cast\"+5"
        }
    }, 
    [10]={
        ["log_name"]="eschite gauntlets", 
        ["count"]=1, 
        ["id"]=27097, 
        ["name"]="eschite gauntlets", 
        ["augments"]={
            [1]="Mag. Evasion+15", 
            [2]="Spell interruption rate down +15%", 
            [3]="Enmity+7"
        }
    }, 
    [11]={
        ["log_name"]="chozoron coselete", 
        ["id"]=26971, 
        ["name"]="chozor. coselete", 
        ["count"]=1
    }
}