-- Generated by the Organizer Library (Sat Dec 29 15:27:47 2018)
return {
    [1]={
        ["log_name"]="kurys gloves", 
        ["id"]=27134, 
        ["name"]="kurys gloves", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="amm greaves", 
        ["count"]=1, 
        ["id"]=27491, 
        ["name"]="amm greaves", 
        ["augments"]={
            [1]="HP+50", 
            [2]="VIT+10", 
            [3]="Accuracy+15", 
            [4]="Damage taken-2%"
        }
    }, 
    [3]={
        ["log_name"]="ishvara earring", 
        ["id"]=27537, 
        ["name"]="ishvara earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="founder's breastplate", 
        ["count"]=1, 
        ["id"]=27910, 
        ["name"]="found. breastplate", 
        ["augments"]={
            [1]="Accuracy+14", 
            [2]="Mag. Acc.+13", 
            [3]="Attack+14", 
            [4]="\"Mag.Atk.Bns.\"+14"
        }
    }, 
    [5]={
        ["log_name"]="chozoron coselete", 
        ["id"]=26971, 
        ["name"]="chozor. coselete", 
        ["count"]=1
    }
}