gambits["WHM"] = {
  {"SELF","STATUS","Silence","ITEM","Echo Drops"}, 
  {"SELF","STATUS","Paralysis","MA","Paralyna"},
  {"CLUSTER","HPP <=",50,"MA","Curaga V"}, -- Oh my god, everyone is dying.
  {"CLUSTER","HPP <=",70,"MA","Curaga IV"},
  {"CLUSTER","HPP <=",80,"MA","Curaga III"},
  {"TANK","STATUS","Doom","MA","Cursna"}, -- Need to keep the tank up.
  {"SELF","STATUS","Doom","MA","Cursna"}, -- Need to keep us up so we can keep tank up.
  {"TANK","HPP <=",20,"MA","Cure VI"},
  {"TANK","HPP <=",40,"MA","Cure V"},
  {"TANK","HPP <=",50,"MA","Cure IV"},
  {"TANK","HPP <=",50,"MA","Cure III"},
  {"MELEE","STATUS","Doom","MA","Cursna"}, -- Weakened melees hurts our DPS moreso than weak mages.
  {"PARTY","STATUS","Doom","MA","Cursna"}, -- Everyone else is expendable.
  {"MELEE","HPP <=",20,"MA","Cure VI"},
  {"MELEE","HPP <=",40,"MA","Cure V"},
  {"MELEE","HPP <=",50,"MA","Cure IV"},
  {"MELEE","HPP <=",50,"MA","Cure III"},
  {"PARTY","HPP <=",20,"MA","Cure VI"},
  {"PARTY","HPP <=",40,"MA","Cure V"},
  {"PARTY","HPP <=",50,"MA","Cure IV"},
  {"PARTY","HPP <=",50,"MA","Cure III"},
  {"SELF","NOT_STATUS","Reraise","MA","Reraise IV"},
  {"SELF","NOT_STATUS","Reraise","MA","Reraise III"},
  {"SELF","NOT_STATUS","Afflatus Solace","JA","Afflatus Solace"},
  {"SELF","NOT_STATUS","Light Arts","JA","Light Arts"},
  {"CLUSTER","STATUS","Sleep","MA","Curaga"},
  --{"AND",{{"PARTY","STATUS","Sleep"},{"PARTY","NOT_STATUS","Charm"}},"","MA","Cure"}
  {"PARTY","STATUS","Petrification","MA","Stona"},
  {"MAGE","STATUS","Silence","MA","Silena"},
  {"TANK","STATUS","Curse","MA","Cursna"},
  {"TANK","STATUS","Bane","MA","Cursna"},
  {"TANK","STATUS","Max HP Down","MA","Erase"},
  {"MELEE","STATUS","Curse","MA","Cursna"},
  {"MELEE","STATUS","Bane","MA","Cursna"},
  {"MELEE","STATUS","Max HP Down","MA","Erase"},
  {"PARTY","HPP <=",75,"MA","Cure IV"},
  {"PARTY","STATUS","Curse","MA","Cursna"},
  {"PARTY","STATUS","Bane","MA","Cursna"},
  {"PARTY","STATUS","Max HP Down","MA","Erase"},
  {"SELF","NOT_STATUS","Haste","MA","Haste"},
  {"SELF","STATUS","Slow","MA","Erase"}, -- Slow on us will slow down removal on everyone.
  {"SELF","STATUS","Addle","MA","Erase"}, -- Same for Addle
  {"TANK","STATUS","Slow","MA","Erase"},
  {"MELEE","STATUS","Slow","MA","Erase"},
  {"PARTY","STATUS","Slow","MA","Erase"},
  {"TANK","STATUS","Paralyzed","MA","Paralyna"},
  {"MELEE","STATUS","Paralyzed","MA","Paralyna"},
  {"PARTY","STATUS","Paralyzed","MA","Paralyna"},
  {"SELF","STATUS","Bind","MA","Erase"}, -- We may need to move into/out of range. Us first.
  {"MELEE","STATUS","Bind","MA","Erase"},
  {"TANK","STATUS","Bind","MA","Erase"},
  {"PARTY","STATUS","Bind","MA","Erase"},
  {"TANK","STATUS","Magic Def. Down","MA","Erase"},
  {"MELEE","STATUS","Magic Def. Down","MA","Erase"},
  {"TANK","STATUS","Magic Evasion Down","MA","Erase"},
  {"MELEE","STATUS","Magic Evasion Down","MA","Erase"},  
  {"TANK","STATUS","Defense Down","MA","Erase"},
  {"MELEE","STATUS","Defense Down","MA","Erase"},
  {"PARTY","STATUS","Magic Def. Down","MA","Erase"},
  {"PARTY","STATUS","Defense Down","MA","Erase"},
  {"PARTY","STATUS","Magic Evasion Down","MA","Erase"},
  {"MAGE","STATUS","Addle","MA","Erase"},
  {"MELEE","STATUS","Weight","MA","Erase"},
  {"TANK","STATUS","Weight","MA","Erase"},
  {"PARTY","STATUS","Weight","MA","Erase"},
  {"MELEE","STATUS","Blindness","MA","Blindna"},
  {"RANGED","STATUS","Blindness","MA","Blindna"},
  {"TANK","STATUS","Blindness","MA","Blindna"},
  {"MELEE","STATUS","Plague","MA","Viruna"},
  {"TANK","STATUS","Plague","MA","Viruna"},
  {"MELEE","STATUS","Accuracy Down","MA","Erase"},
  {"TANK","STATUS","Accuracy Down","MA","Erase"},
  {"RANGED","STATUS","Accuracy Down","MA","Erase"},
  {"MAGE","STATUS","Magic Acc. Down","MA","Erase"},
  {"MELEE","STATUS","Attack Down","MA","Erase"},
  {"MAGE","STATUS","Magic Atk. Down","MA","Erase"},
  {"RANGED","STATUS","Attack Down","MA","Erase"},
  {"SELF","STATUS","Plague","MA","Viruna"},
  {"PARTY","STATUS","Plague","MA","Viruna"},
  {"PARTY","HPP <=",85,"MA","Cure III"},
  {"PARTY","STATUS","Poison","MA","Poisona"},
  {"MELEE","NOT_STATUS","Haste","MA","Haste"},
  {"TANK","NOT_STATUS","Haste","MA","Haste"},
  --{"PARTY","NOT_STATUS","Regen","MA","Regen IV"}
}